import type {Ref} from "vue";
import {ref} from "vue";

export interface Translation {
    settingsSaved: string;
    login: string;
    email: string;
    password: string;
    confirmPassword: string;
    keepLoggedIn: string;
    haveAnInvite: string;
    resetPassword: string;

    new: string;
    edit: string;
    save: string;
    delete: string;
    cancel: string;
    confirm: string;
    confirmDelete: string;
    history: string;
    autoGenerated: string;

    userSettings: string;
    privateModeActiveOnLoad: string;
    previewActiveOnLoad: string;
    sortingAscendingOnLoad: string;

    invite: string;
    createInvite: string;

    validUntil: string;
    deposit: string;
    depositTitle: string;
    withdraw: string;
    withdrawalTitle: string;

    unnamed: string;

    creationDate: string;
    bookingDate: string;
    value: string;
    value19: string;
    value7: string;
    vat19: string;
    vat7: string;
    note: string;

    firstExecution: string;
    nextExecution: string;
    lastExecution: string;

    recurringDeleteTransactionsCascasing: string;

    category: string;
    categoryCreatedSuccess: string;
    categoryUpdatedSuccess: string;
    categoryDeletedSuccess: string;
}

export const languages: {[languageCode: string]: Translation} = {
    'en-US': {
        settingsSaved: 'Settings saved',
        login: 'Login',
        email: 'E-Mail',
        password: 'Password',
        confirmPassword: 'Confirm password',
        keepLoggedIn: 'Keep logged in',
        haveAnInvite: 'I have an invite',
        resetPassword: 'Reset password',
        new: 'New',
        edit: 'Edit',
        save: 'Save',
        delete: 'Delete',
        cancel: 'Cancel',
        confirm: 'Confirm',
        confirmDelete: 'Confirm delete (I am really sure!)',
        history: 'History',
        autoGenerated: '<auto-generated>',
        userSettings: 'User settings',
        privateModeActiveOnLoad: 'Private mode active by default',
        previewActiveOnLoad: 'Preview active by default',
        sortingAscendingOnLoad: 'Sort ascending by default',
        invite: 'Invite',
        createInvite: 'Create invite',
        validUntil: 'Valid until',
        deposit: 'Deposit',
        depositTitle: 'Deposit',
        withdraw: 'Withdraw',
        withdrawalTitle: 'Withdrawal',
        unnamed: 'Unnamed',
        creationDate: 'Creation date',
        bookingDate: 'Booking date',
        value: 'Value',
        value19: 'Value 19%',
        value7: 'Value 7%',
        vat19: 'VAT 19%',
        vat7: 'VAT 7%',
        note: 'Note',
        firstExecution: 'First execution',
        nextExecution: 'Next execution',
        lastExecution: 'Last execution',
        recurringDeleteTransactionsCascasing: 'Delete all transactions belonging to this recurring payment, even if they lie in the past',
        category: 'Category',
        categoryCreatedSuccess: 'Category created successfully',
        categoryUpdatedSuccess: 'Category saved successfully',
        categoryDeletedSuccess: 'Category deleted successfully',
    },
    'de-DE': {
        settingsSaved: 'Einstellungen gespeichert',
        login: 'Anmelden',
        email: 'E-Mail',
        password: 'Passwort',
        confirmPassword: 'Passwort bestätigen',
        keepLoggedIn: 'Angemeldet bleiben',
        haveAnInvite: 'Ich habe eine Einladung',
        resetPassword: 'Password zurücksetzen',
        new: 'Neu',
        edit: 'Bearbeiten',
        save: 'Speichern',
        delete: 'Löschen',
        cancel: 'Abbrechen',
        confirm: 'Bestätigen',
        confirmDelete: 'Löschen bestätigen (Ich bin mir sicher!)',
        history: 'Historie',
        autoGenerated: '<auto-generiert>',
        userSettings: 'Nutzer Einstellungen',
        privateModeActiveOnLoad: 'Privater Modus aktiv wenn Seite geladen wird',
        previewActiveOnLoad: '"Vorschau" aktiv wenn Seite geladen wird',
        sortingAscendingOnLoad: 'Sortierung aufsteigend wenn Seite geladen wird',
        invite: 'Einladung',
        createInvite: 'Einladung erstellen',
        validUntil: 'Gültig bis',
        deposit: 'Einzahlen',
        depositTitle: 'Einzahlung',
        withdraw: 'Auszahlen',
        withdrawalTitle: 'Auszahlung',
        unnamed: 'Unbenannt',
        creationDate: 'Erstelldatum',
        bookingDate: 'Buchungsdatum',
        value: 'Betrag',
        value19: 'Betrag 19%',
        value7: 'Betrag 7%',
        vat19: 'MwSt 19%',
        vat7: 'MwSt 7%',
        note: 'Notiz',
        firstExecution: 'Erste Ausführung',
        nextExecution: 'Nächste Ausführung',
        lastExecution: 'Letzte Ausführung',
        recurringDeleteTransactionsCascasing: 'Alle Transaktionen dieses Dauerauftrags löschen, auch wenn diese in der Vergangenheit liegen',
        category: 'Kategorie',
        categoryCreatedSuccess: 'Kategorie erfolgreich erstellt',
        categoryUpdatedSuccess: 'Kategorie erfolgreich gespeichert',
        categoryDeletedSuccess: 'Kategorie erfolgreich gelöscht',
    },
};

export const lang: Ref<Translation> = ref(languages['en-US']);
